Repository punker76/gong-wpf-dragdrop, pull requests merged in 2018-10, with the labels that each got.

#300 Add dependency property DropEventType
  src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
  src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
  src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
  src/GongSolutions.WPF.DragDrop.Shared/EventType.cs
  src/GongSolutions.WPF.DragDrop.Shared/GongSolutions.WPF.DragDrop.Shared.projitems
  src/GongSolutions.WPF.DragDrop.Shared/IDropInfo.cs
Labels: Hacktoberfest

#297 Added DropTargetScrollViewer property
  src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
  src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
Labels: Enhancement

#296 DropTargetInsertionAdorner is short
  src/GongSolutions.WPF.DragDrop.Shared/DropTargetInsertionAdorner.cs
  src/GongSolutions.WPF.DragDrop.Shared/Utilities/ItemsControlExtensions.cs
Labels: Bug :beetle:

#285 Make dragInfo available in custom drag adorner template selector
  src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
  src/GongSolutions.WPF.DragDrop.Shared/Utilities/DragDropExtensions.cs
Labels: Enhancement

#273 Optimization in Drop method of DefaultDropHandler
  src/GongSolutions.WPF.DragDrop.Shared/DefaultDropHandler.cs
Labels: Enhancement
