Repository punker76/gong-wpf-dragdrop, pull requests merged in 2021-12, with the labels that each got.

#421 Enable dragging of ToggleButton controls
  src/GongSolutions.WPF.DragDrop/DragDrop.cs
  src/Showcase/Models/ItemModel.cs
  src/Showcase/Views/Issues.xaml
Labels: Bug Fix

#422 Drop .Net 4.5.2 and 4.6 target
  appveyor.yml
  build.cake
  src/Directory.build.props
  src/GongSolutions.WPF.DragDrop/Directory.Build.props
  src/GongSolutions.WPF.DragDrop/GongSolutions.WPF.DragDrop.csproj
  src/GongSolutions.WPF.DragDrop/Utilities/DpiHelper.cs
  src/GongSolutions.WPF.DragDrop/Utilities/DragDropExtensions.cs
Labels: Breaking Change, Feature

#423 Update supported frameworks in README
  README.md
Labels: Doc
