Repository punker76/gong-wpf-dragdrop, pull requests merged in 2024-12, with the labels that each got.

#497 Always correctly reset state when drag is cancelled
  src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
  src/GongSolutions.WPF.DragDrop/DragDrop.cs
Labels: Bug Fix

#502 Threading Problem
  src/GongSolutions.WPF.DragDrop/DropTargetAdorner.cs
Labels: Bug Fix

#505 Typo Detatch -> Detach in DropTargetAdorner corrected
  src/GongSolutions.WPF.DragDrop/DragDrop.cs
  src/GongSolutions.WPF.DragDrop/DropTargetAdorner.cs
Labels: Breaking Change

#453 Add logic to disallow child items in tree views
  src/GongSolutions.WPF.DragDrop/DropInfo.cs
  src/GongSolutions.WPF.DragDrop/IDropInfo.cs
  src/Showcase/Models/FilesDropHandler.cs
  src/Showcase/Models/SampleData.cs
  src/Showcase/Models/TreeNode.cs
  src/Showcase/Views/TreeViewSamples.xaml
Labels: Enhancement

#489 DropTarget hint and DropHighlightAdorner background brush
  README.md
  screenshots/DragHint-Demo.gif
  src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
  src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
  src/GongSolutions.WPF.DragDrop/DragDrop.cs
  src/GongSolutions.WPF.DragDrop/DragInfo.cs
  src/GongSolutions.WPF.DragDrop/DropHintData.cs
  src/GongSolutions.WPF.DragDrop/DropHintHelpers.cs
  src/GongSolutions.WPF.DragDrop/DropHintInfo.cs
  src/GongSolutions.WPF.DragDrop/DropHintState.cs
  src/GongSolutions.WPF.DragDrop/DropInfo.cs
  src/GongSolutions.WPF.DragDrop/DropTargetAdorner.cs
  src/GongSolutions.WPF.DragDrop/DropTargetAdorners.cs
  src/GongSolutions.WPF.DragDrop/DropTargetHighlightAdorner.cs
  src/GongSolutions.WPF.DragDrop/DropTargetHintAdorner.cs
  src/GongSolutions.WPF.DragDrop/DropTargetHintWeakReference.cs
  src/GongSolutions.WPF.DragDrop/IDropHintInfo.cs
  src/GongSolutions.WPF.DragDrop/IDropInfo.cs
  src/GongSolutions.WPF.DragDrop/IDropTarget.cs
  src/GongSolutions.WPF.DragDrop/IDropTargetItemsSorter.cs
  src/Showcase/Models/CustomDropHintHandler.cs
  src/Showcase/Models/GroupedDropHandler.cs
  src/Showcase/Models/NestedDropHandler.cs
  src/Showcase/Models/SampleData.cs
  src/Showcase/Models/SerializableDropHandler.cs
  src/Showcase/Models/TextBoxCustomDropHandler.cs
  src/Showcase/Views/MixedSamples.xaml
  src/Showcase/Views/SettingsView.xaml
  src/Showcase/Views/TreeViewSamples.xaml
Labels: Feature

#424 Enable custom IDragInfo & IDropInfo implementations
  src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
  src/GongSolutions.WPF.DragDrop/DragDrop.cs
  src/GongSolutions.WPF.DragDrop/DragInfo.cs
  src/GongSolutions.WPF.DragDrop/DropInfo.cs
  src/GongSolutions.WPF.DragDrop/DropTargetAdorner.cs
  src/GongSolutions.WPF.DragDrop/DropTargetInsertionAdorner.cs
  src/GongSolutions.WPF.DragDrop/IDragInfo.cs
  src/GongSolutions.WPF.DragDrop/IDragInfoBuilder.cs
  src/GongSolutions.WPF.DragDrop/IDragSource.cs
  src/GongSolutions.WPF.DragDrop/IDropInfoBuilder.cs
  src/GongSolutions.WPF.DragDrop/IDropTarget.cs
  src/Showcase/Models/TextBoxCustomDropHandler.cs
Labels: Breaking Change

#506 Set target to net462, net6 and net8
  .config/dotnet-tools.json
  .github/workflows/ci.yml
  GitVersion.yml
  NuGet.Config
  README.md
  appveyor.yml
  build.cake
  cake.config
  global.json
  src/Directory.build.props
  src/Directory.build.targets
  src/Directory.packages.props
  src/GongSolutions.WPF.DragDrop.sln
  src/Showcase/FodyWeavers.xsd
  src/Showcase/Showcase.WPF.DragDrop.csproj
  src/Showcase/Views/TreeViewSamples.xaml
  src/global.json
Labels: Breaking Change
